### ISSUE TITLE
Make it a haskell stack project

### ISSUE THREAD

**Issue by schoettl** [dpaetzel/aq2ledger#1]
Hi,

could you make this project a haskell stack project? It seems best practice to use stack for haskell projects. Currently, I cannot build it. Errors over errors. With stack it usually just works.

**Comment by dpaetzel** [comment]
I added building with stack; let me know whether it works for you. Besides, there was a module in `aq2ledger.cabal` that shouldn't have been there which probably led to some of the errors you encountered.

**Comment by schoettl** [comment]
Thanks, now it compiles without problems (`stack build`)!
